#!/usr/bin/perl
#
# Copyright 2015 Vaara-kirjastot
#
# This file is part of Koha.
#
# Koha is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# Koha is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with Koha; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

use Modern::Perl;
use CGI;
use C4::Auth;
use C4::Context;
#use Data::Dumper;
use JSON;

my $query = new CGI;
my $kohasessionid = $query->param('kohasessionid');
my $kohausername = $query->param('kohauser');

#my $kohasessionid = "cab689dfafac10285ac5eec417e063dc";
#my $kohausername = "super";
my $json_text;

if ($kohasessionid && $kohausername) {
  my $session = C4::Auth::get_session($kohasessionid);
  my $flags = {
    catalogue => '*'
  };
#  my ($status, $sessionid) = C4::Auth::check_cookie_auth($kohasessionid, $flags);

#  if ($status && $status == "ok" && $kohasessionid eq $sessionid) {
  if ($kohasessionid eq $session->param('_SESSION_ID')) {
#    print Dumper($session);
#    $json_text = to_json($session);
#    my $session = C4::Auth::get_session($sessionid);
    my $response = {
                    username => $session->param('id'),
                    sessionid => $session->param('_SESSION_ID'),
                    firstname => $session->param('firstname'),
                    surname => $session->param('surname'),
                    emailaddress => $session->param('emailaddress'),
                  };
    $json_text = encode_json $response;
  }
  else {
    $session->delete();
    $session->flush();
    my $response = {
      badsessionid => 1
    };
    $json_text = to_json $response;
  }
}
else {
  my $response = {
    paramsmissing => 1
  };
  $json_text = encode_json $response;
}

binmode STDOUT, ":encoding(UTF-8)";
print $query->header(
    -type => 'application/json',
    -charset => 'UTF-8'
);

print $json_text;
